# Generated by Django 5.0.6 on 2025-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('other', 'Other')], default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
